config/routes.rb
LezipuNet::Application.routes.draw do
  resources :shops

end

app/models/shop.rb
class Shop < ActiveRecord::Base
	validates_presence_of :address, :phone, :open_time, :brief,:name
	has_attached_file :photo1, :styles =>{:big =>"320x240>", :thumb => "80x80>"}
	has_attached_file :photo2, :styles =>{:big =>"320x240>", :thumb => "80x80>"}
	has_attached_file :photo3, :styles =>{:big =>"320x240>", :thumb => "80x80>"}
	validates_attachment_presence :photo1
	validates_attachment_size :photo1, :less_than =>3.megabytes
	validates_attachment_content_type :photo1, :content_type => ['image/jpeg', 'image/png','image/gif','image/pjpeg', 'image/x-png']
	validates_attachment_size :photo2, :less_than =>3.megabytes
	validates_attachment_content_type :photo2, :content_type => ['image/jpeg', 'image/png','image/gif','image/pjpeg', 'image/x-png']
	validates_attachment_size :photo3, :less_than =>3.megabytes
	validates_attachment_content_type :photo3, :content_type => ['image/jpeg', 'image/png','image/gif','image/pjpeg', 'image/x-png']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/shops_controller.rb
#encoding = utf-8
class ShopsController < ApplicationController
	before_filter :authenticate, :only=>'index'
	
  # GET /shops
  # GET /shops.xml
  def index
    @shops = Shop.find(:all).paginate :per_page => 10 , :page => params[:page]


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @shops }
    end
  end

  # GET /shops/1
  # GET /shops/1.xml
  def show
    @shop = Shop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @shop }
    end
  end

  # GET /shops/new
  # GET /shops/new.xml
  def new
    @shop = Shop.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @shop }
    end
  end

  # GET /shops/1/edit
  def edit
    @shop = Shop.find(params[:id])
  end

  # POST /shops
  # POST /shops.xml
  def create
    @shop = Shop.new(params[:shop])

    respond_to do |format|
      if @shop.save
        format.html { redirect_to(@shop, :notice => '店铺新增成功！') }
        format.xml  { render :xml => @shop, :status => :created, :location => @shop }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @shop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shops/1
  # PUT /shops/1.xml
  def update
    @shop = Shop.find(params[:id])

    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        format.html { redirect_to(@shop, :notice => '店铺修改成功！') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @shop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.xml
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to(shops_url) }
      format.xml  { head :ok }
    end
  end
  
  protected
  def authenticate
  	authenticate_or_request_with_http_basic do |username, password|
  		username=='lezipu' && password=='lvdong'
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<%= csrf_meta_tag %>
<meta content="all" name="robots" />
<link rel="stylesheet" type="text/css" media="all" href="http://www.lezipu.com/css/framework/basic.css">
<link rel="stylesheet" type="text/css" media="all" href="http://www.lezipu.com/css/framework/component.css">
<%= javascript_include_tag :defaults %>

</head>
<body>
<%= yield %>
</body>
</html>

app/views/shops/_form.html.erb
<%= form_for @shop, :html=>{:multipart=>true} do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2>以下有<%= @shop.errors.count %>个必填项目，请补充完整,必须提供至少一张图片:</h2>

      <!-- <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul> -->
    </div>
  <% end %>
  <p class="headsup"><span class="highlight">***</span>号为必填项目,必须提供至少一张图片，支持格式jpeg、gif、png:</p>
  <div class="field">
    <div><%= f.label :名称 %><span>***</span></div>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <div><%= f.label :地址 %><span>***</span></div>
    <%= f.text_field :address %>
  </div>
    <div class="field">
    <div><%= f.label :商圈（地标等补充信息） %></div>
    <%= f.text_field :land_mark %>
  </div>
  <div class="field">
    <div><%= f.label :电话 %><span>***</span></div>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <div><%= f.label :营业时间 %><span>***</span></div>
    <%= f.text_field :open_time %>
  </div>
  <div class="field">
    <div><%= f.label :商户简介 %><span>***</span></div>
    <%= f.text_area :brief %>
  </div>
  
  <div class="field">
    <div><%= f.label "图片1" %><span>***</span></div>
    <%= f.file_field :photo1 %>
  </div>
  <div class="field">
    <div><%= f.label "图片2" %></div>
    <%= f.file_field :photo2 %>
  </div>
  <div class="field">
    <div><%= f.label "图片3" %></div>
    <%= f.file_field :photo3 %>
  </div>
  
  <div class="field">
    <div><%= f.label :email邮箱 %></div>
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <div><%= f.label :Msn %></div>
    <%= f.text_field :msn %>
  </div>
  <div class="field">
    <div><%= f.label :QQ %></div>
    <%= f.text_field :qq %>
  </div>
  <div class="actions">
    <%= f.submit "确认提交" %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>编辑店铺</h1>

<%= render 'form' %>

app/views/shops/index.html.erb
<h1>店铺列表</h1>

<table>
  <tr>
    <th>名称：</th>
    <th>地址：</th>
    <th>商圈/地标：</th>
    <th>电话：</th>
    <th>营业时间：</th>
    <th>简介：</th>
    <th>Email</th>
    <th>Msn</th>
    <th>Qq</th>
    <th>图片1</th>
    <th>图片2</th>
    <th>图片3</th>
  </tr>

<% @shops.each do |shop| %>
  <tr>
    <td><%= shop.name %></td>
    <td><%= shop.address %></td>
    <td><%= shop.land_mark %></td>
    <td><%= shop.phone %></td>
    <td><%= shop.open_time %></td>
    <td><%= shop.brief %></td>
    <td><%= shop.email %></td>
    <td><%= shop.msn %></td>
    <td><%= shop.qq %></td>
    <td><%= image_tag shop.photo1.url(:thumb)%></td>
    <td><% if shop.photo2_file_name%><%= image_tag shop.photo2.url(:thumb)%><% end %></td>
    <td><% if shop.photo3_file_name%><%= image_tag shop.photo3.url(:thumb)%><% end %></td>
    
    <td><%= link_to '预览', shop %></td>
    <td><%= link_to '编辑', edit_shop_path(shop) %></td>
    <td><%= link_to '删除', shop, :confirm => '确认删除?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @shops%>
<br />

<%= link_to '新增店铺', new_shop_path %>

app/views/shops/new.html.erb
<h1>添加新店铺</h1>

<%= render 'form' %>

app/views/shops/show.html.erb
<div class="newshop_content">
<p id="notice"><%= notice %></p>

<p>
  <span>名称:</span>
  <%= @shop.name %>
</p>

<p>
  <span>地址:</span>
  <%= @shop.address %>
</p>

<p>
  <span>商圈/地标:</span>
  <%= @shop.land_mark%>
</p>

<p>
  <span>联系电话:</span>
  <%= @shop.phone %>
</p>

<p>
  <span>营业时间:</span>
  <%= @shop.open_time %>
</p>

<p>
  <span>店铺简介:</span>
  <%= @shop.brief %>
</p>

<p>
  <span>图片:</span>
  <%= image_tag @shop.photo1.url(:big),:class=>"addshoppic"%>
  <% if @shop.photo2_file_name%>
 	 <%= image_tag @shop.photo2.url(:big),:class=>"addshoppic"%>
  <% end %>
  <% if @shop.photo3_file_name%>
  	<%= image_tag @shop.photo3.url(:big),:class=>"addshoppic"%>
  <% end %>
</p>

<p>
  <span>Email:</span>
  <%= @shop.email %>
</p>

<p>
  <span>Msn:</span>
  <%= @shop.msn %>
</p>

<p>
  <span>Qq:</span>
  <%= @shop.qq %>
</p>

<div>
	<%= link_to '修改', edit_shop_path(@shop), :class=>"button green edit" %> 
	<%= link_to '继续添加店铺', new_shop_path, :class=>"button green addnew" %>
	<a class="button green" href="http://www.lezipu.com">返回首页</a></div>
</div>